platform :ios, '12.0'
use_frameworks!

# Add Application pods here
def app_pods
    pod 'Alamofire', '~> 4.8'
    pod 'AlamofireImage', '~> 3.5'
    pod 'AsyncSwift', '~> 2.0'
    pod 'Crashlytics'
    pod 'Device', '~> 3.0'
    pod 'DynamicColor', '~> 4.0'
    pod 'Eureka', '~> 5.0'
    pod 'Fabric', '~> 1.9'
    pod 'KeychainAccess', '~> 4.0'
    pod 'NVActivityIndicatorView', '~> 4.0'
    pod 'R.swift', '~> 5.0.2'
    pod 'Result', '~> 4.0'
    pod 'RxAlamofire', '~> 5.0'
    pod 'RxCocoa', '~> 5.0'
    pod 'RxSwift', '~> 5.0'
    pod 'SwiftDate', '~> 6.0'
    pod 'SwiftyUserDefaults', '~> 5.0'
    pod 'Action', '~> 4.0'
end

def testing_pods
    pod 'Quick', '~> 2.0'
    pod 'Nimble', '~> 8.0'
end

target 'XLProjectName' do
  app_pods
end

target 'XLProjectName-Staging' do
  app_pods
end

target 'Tests' do
  testing_pods
end

target 'UITests' do
  testing_pods
end
