platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

# Add Application pods here
def app_pods
    pod 'Alamofire', '~> 5.0'
    pod 'AlamofireImage', '~> 4.0'
    pod 'AsyncSwift', '~> 2.0'
    pod 'Device', '~> 3.0'
    pod 'DynamicColor', '~> 4.0'
    pod 'Eureka', '~> 5.0'
    pod 'Fabric', '~> 1.10.2'
    pod 'Crashlytics', '~> 3.14.0'
    # (Recommended) Pod for Google Analytics
    pod 'Firebase/Analytics'
    pod 'KeychainAccess', '~> 4.0'
    pod 'NVActivityIndicatorView', '~> 4.0'
    pod 'R.swift', '~> 5.0.2'
    pod 'RxCocoa', '~> 5.0'
    pod 'RxSwift', '~> 5.0'
    pod 'SwiftDate', '~> 6.0'
    pod 'SwiftyUserDefaults', '~> 5.0'
    pod 'Action', '~> 4.0'
end

def testing_pods
    pod 'Quick', '~> 2.0'
    pod 'Nimble', '~> 8.0'
end

target 'XLProjectName' do
  app_pods
end

target 'Tests' do
  testing_pods
end

target 'UITests' do
  testing_pods
end

#setting for mac m1

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      # 消除文档警告
      config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
      # 解决证书 报错问题 或 使用其他方案
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      #config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      target.build_settings(config.name)['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
